#frequency: 100.0
frequency: 15.0
frame_id: "ce30c"
#frame_id: "astrobot_front_rgbd_camera_link"
scan_topic: "/astrobot/front_laser/scan"
publish_markers: true
bearing_std_dev: 0.02
range_std_dev: 0.000012
least_sq_angle_thresh: 0.00001
least_sq_radius_thresh: 0.00001
max_line_gap: 0.5
min_line_length: 0.5
min_range: 0.05
min_split_dist: 0.3
outlier_dist: 0.1
min_line_points: 30
