#frequency: 100.0
frequency: 15.0
frame_id: "rb1_base_front_laser_link"
scan_topic: "/rb1_base/scan_for_lines"
publish_markers: true
bearing_std_dev: 0.00001
range_std_dev: 0.012
least_sq_angle_thresh: 0.00001
least_sq_radius_thresh: 0.00001
max_line_gap: 0.25
min_line_length: 0.38
min_range: 0.4
min_split_dist: 0.24
outlier_dist: 0.4
min_line_points: 20
