#frequency: 100.0
frequency: 15.0
frame_id: "rb1_base_front_laser_link"
scan_topic: "/rb1_base/front_laser/scan"
publish_markers: true
bearing_std_dev: 0.00001
range_std_dev: 0.012
least_sq_angle_thresh: 0.00001
least_sq_radius_thresh: 0.00001
max_line_gap: 0.25
min_line_length: 0.5
min_range: 0.5
min_split_dist: 0.04
outlier_dist: 0.08
min_line_points: 10
